--1
SELECT Nome, Ano FROM Filmes;

--2
SELECT NOME, ANO FROM FILMES ORDER BY ANO;

--3
SELECT NOME, ANO, DURACAO FROM FILMES WHERE NOME LIKE 'DE VOLTA%';

--4
SELECT * FROM FILMES WHERE ANO = 1997;

--5
SELECT * FROM FILMES WHERE ANO > 2000;

--6
SELECT * FROM FILMES WHERE DURACAO > 100 AND DURACAO < 150 ORDER BY DURACAO;

--7
SELECT ANO, COUNT(*) AS QUANTIDADE FROM FILMES GROUP BY ANO ORDER BY COUNT(*) DESC;

--8
SELECT * FROM ATORES WHERE GENERO = 'M';

--9
SELECT * FROM ATORES WHERE GENERO = 'F' ORDER BY PRIMEIRONOME;

--10
SELECT F.NOME, G.GENERO FROM FILMES F JOIN FILMESGENERO FG ON F.ID = FG.IDFILME JOIN GENEROS G ON G.ID = FG.IDGENERO;

--11
SELECT F.NOME, G.GENERO FROM FILMES F JOIN FILMESGENERO FG ON F.ID = FG.IDFILME JOIN GENEROS G ON G.ID = FG.IDGENERO
WHERE G.GENERO = 'MISTÉRIO';

--12
SELECT F.NOME, A.PRIMEIRONOME, A.ULTIMONOME, E.PAPEL FROM FILMES F JOIN ELENCOFILME E ON (E.IDFILME = F.ID) JOIN ATORES A ON (E.IdAtor = A.ID);